version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: cmi-nginx
    depends_on:
      - cmi
    networks:
      - cmi
    volumes:
      - ./:/srv/app
      - ./docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/nginx/certificat:/opt/certificat
    ports:
      - "8080:80"
      - "8443:443"
  
  cmi:
    build:
      context: ./docker/app
    container_name: cmi-app
    volumes:
      - ./:/srv/app
    depends_on:
      - database
    networks:
      - cmi

  database:
    container_name: cmi-db
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - cmi_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    networks:
      - cmi

volumes:
  cmi_data:

networks:
  cmi:
